spring:
  datasource:
    url: jdbc:mysql://www.sxsugon.cn:3306/passbook?autoReconnect=true
    username: user
    password: Sx147sugon258
  application:
    name: ImoocMerchants
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4
server:
  port: 8080
logging:
  level: debug
  file: imooc-merchants.log
